repos:
   - repo: local
     hooks:
       - id: run-tests
         name: Run Tests
         entry: ./env/bin/pytest -m "not expensive"
         language: python  # or 'python' if you want a specific environment
         types: [python]
         pass_filenames: false
