repos:
   - repo: local
     hooks:
       - id: run-tests
         name: Run Tests
         entry: env/bin/pytest
         language: system  # or 'python' if you want a specific environment
         types: [python]
